enableGlobalCache: true

npmRegistryServer: 'https://registry.npm.taobao.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-2.4.0.cjs
